spring:
  config:
    #    https://medium.com/@Marou_arnault/spring-boot-hide-your-credentials-fb1ca22ae911
    import: file:prod.env.yaml
  datasource:
#    url: "jdbc:mysql://scaler-project-module-db.c8flxv6z8gbz.us-east-1.rds.amazonaws.com/products?createDatabaseIfNotExist=true"
#    username: "admin"
#    password: "adminadmin"
    url: "jdbc:sqlite:productservice_prod_DB.sqlite"
    username: "sa"
    password: "sa"
# Redis
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}


# Eureka Client
# https://cloud.spring.io/spring-cloud-netflix/reference/html/#spring-cloud-eureka-server-standalone-mode
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: "https://servicediscovery-manthan.azurewebsites.net/eureka/"